apiVersion: v1
kind: ConfigMap
metadata:
  name: study-config
  labels:
    app: study-service
data:
  # Server
  SERVER_PORT: "8082"

  # Spring Application
  SPRING_APPLICATION_NAME: "study-service"

  # Database
  SPRING_DATASOURCE_URL: "jdbc:postgresql://k8s-db.cfy4s0q4ylzv.ap-northeast-2.rds.amazonaws.com:5432/growple?currentSchema=public"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"

  # JPA
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  SPRING_JPA_SHOW_SQL: "false"

  # Redis
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"

  # Kafka
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_KAFKA_CONSUMER_GROUP_ID: "study-service-group"

  # Eureka
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://discovery-service:8761/eureka"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"

  # Logging
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_GROW_STUDY: "INFO"

  # Jackson
  SPRING_JACKSON_TIME_ZONE: "Asia/Seoul"
