apiVersion: apps/v1
kind: Deployment
metadata:
  name: study-service
  labels:
    app: study-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: study-service
  template:
    metadata:
      labels:
        app: study-service
        version: v1
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: study-service
          image: 481207241075.dkr.ecr.ap-northeast-2.amazonaws.com/growple/study-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
              protocol: TCP
          envFrom:
            - configMapRef:
                name: study-config
            - secretRef:
                name: study-secret

#          resources:
#            requests:
#              memory: "512Mi"
#              cpu: "250m"
#            limits:
#              memory: "1Gi"
#              cpu: "500m"
