apiVersion: v1
kind: Service
metadata:
  name: study-service
  labels:
    app: study-service
spec:
  type: NodePort
  selector:
    app: study-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      nodePort: 30082
      protocol: TCP
