apiVersion: v1
kind: ConfigMap
metadata:
  name: apigateway-config
  labels:
    app: apigateway-service
data:
  # Server
  SERVER_PORT: "8080"

  # Spring Application
  SPRING_APPLICATION_NAME: "apigateway-service"

  # Eureka
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-service:8761/eureka/"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"

  # Logging
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_GROW_APIGATEWAY: "INFO"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY: "INFO"

  # Jackson
  SPRING_JACKSON_TIME_ZONE: "Asia/Seoul"
