apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-service
  labels:
    app: apigateway-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway-service
  template:
    metadata:
      labels:
        app: apigateway-service
        version: v1
    spec:
      containers:
        - name: apigateway-service
          image: apigateway-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: apigateway-config
            - secretRef:
                name: apigateway-secret