apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-service
  labels:
    app: apigateway-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway-service
  template:
    metadata:
      labels:
        app: apigateway-service
        version: v1
    spec:
      imagePullSecrets:
        - name : ecr-secret
      containers:
        - name: apigateway-service
          image: 481207241075.dkr.ecr.ap-northeast-2.amazonaws.com/growple/apigateway-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: apigateway-config
            - secretRef:
                name: apigateway-secret