apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: growple
  labels:
    app: chat-service
spec:
  type: NodePort
  selector:
    app: chat-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
      nodePort: 30084
      protocol: TCP
