

springdoc:
  swagger-ui:
    urls:
      - url: /member-service/v3/api-docs
        name: Member-Service
      - url: /study-service/v3/api-docs
        name: Study-Service
      - url: /payment-service/v3/api-docs
        name: Payment-Service


spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:3000'
              - 'http://localhost:3001'
            allowed-headers: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allow-credentials: true
            exposed-headers:
              - Set-Cookie
              - Authorization



      routes:
        - id: member-service
          predicates:
            - Path=/member-service/**
          filters:
            - StripPrefix=1
          uri: lb://member-service

        - id: study-service
          predicates:
            - Path=/study-service/**
          filters:
            - StripPrefix=1
          uri: lb://study-service

        - id: payment-service
          predicates:
            - Path=/payment-service/**
          filters:
            - StripPrefix=1
          uri: lb://payment-service

        - id: chat-service
          predicates:
            - Path=/chat-service/**
          filters:
            - StripPrefix=1
          uri: lb://chat-service

        - id: chat-service-websocket
          predicates:
            - Path=/ws-chat/**
          uri: lb://chat-service





jwt:
  secretKey: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5
  issuer: growple-gateway
  whitelist-paths:
    - /api/auth/**
    - /api/health
    - /actuator/**
    - /swagger-ui/**
    - /v3/api-docs/**
    - /api/study/get/**
    - /api/study/list
    - /api/study/pages
    - /api/scheduler/**
    - /api/chat/**
    - /ws-chat/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.grow.apigateway: DEBUG
    org.springframework.cloud.gateway: INFO
